- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleTroublemaker
  name: Troublemaker Role
  components:
  - type: MindRole
    antagPrototype: Troublemaker
    exclusiveAntag: true
    roleType: SoloAntagonist
    subtype: role-subtype-troublemaker
  - type: TroublemakerRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleAcolyte
  name: Acolyte Role
  components:
  - type: MindRole
    antagPrototype: Acolyte
    exclusiveAntag: true
    roleType: SoloAntagonist
    subtype: role-subtype-acolyte
  - type: AcolyteRole
