# Box Note: This prototype existed in base namespace, likely from EE. It's been moved to _DEN since that's why we have it.

# A "squeaky toy" is just a toy that squeaks. They lack stashes as well. Plushies are made of fabric and all.

- type: entity
  parent: BaseItem
  id: BaseSqueakyToy
  abstract: true
  components:
  - type: Sprite
    sprite: Objects/Fun/toys.rsi
  - type: Tag
    tags:
      - Payload
  - type: EmitSoundOnUse
    sound:
      collection: ToySqueak
  - type: EmitSoundOnActivate
    sound:
      collection: ToySqueak
  - type: EmitSoundOnCollide
    sound:
      collection: ToySqueak
  - type: EmitSoundOnLand
    sound:
      collection: ToyFall
  - type: EmitSoundOnTrigger
    sound:
      collection: ToySqueak
  - type: UseDelay
    delay: 1.0
  - type: MeleeWeapon
    wideAnimationRotation: 180
    soundHit:
      collection: ToySqueak
    damage:
      types:
        Blunt: 0
  #- type: DamageOtherOnHit # Box Change: Remove this because we're not EE and not everything needs to do throwing damage
  - type: StaticPrice
    price: 5
