# Upstream Antags
## BB
- type: antag
  id: DummyBB
  name: roles-antag-blood-brother-name
  antagonist: true
  setPreference: true
  visiblePreference: true
  objective: roles-antag-blood-brother-objective
  guides: [BloodBrothers]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 3600 # 1h

## LoneOp
#- type: antag
#  id: DummyNukeOps
#  name: roles-antag-box-lone-operative-name
#  antagonist: true
#  setPreference: true
#  visiblePreference: true
#  objective: roles-antag-box-lone-operative-objective
#  guides: [NuclearOperatives]
#  requirements:
#  - !type:OverallPlaytimeRequirement
#    time: 18000 # 5h

## Syndie
- type: antag
  id: DummySyndie
  name: roles-antag-syndicate-agent-name
  antagonist: true
  setPreference: true
  visiblePreference: true
  objective: roles-antag-syndicate-agent-objective
  guides: [Traitors]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 3600 # 1h

- type: antag
  id: DummySyndieSleeper
  name: roles-antag-syndicate-agent-sleeper-name
  antagonist: true
  setPreference: true
  visiblePreference: true
  objective: roles-antag-syndicate-agent-sleeper-objective
  guides: [Traitors]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 3600 # 1h

## Thief
- type: antag
  id: DummyThief
  name: roles-antag-thief-name
  antagonist: true
  setPreference: true
  visiblePreference: true
  objective: roles-antag-thief-objective
  guides: [Thieves]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 3600 # 1h

## DAGD Consent
- type: antag
  id: ConsentDAGD
  name: consent-dagd
  antagonist: true
  setPreference: true
  visiblePreference: true
  objective: consent-dagd-desc
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5h

# Objective Consent
## RR
- type: antag
  id: ConsentBeRRTarget
  name: consent-be-rr-target
  antagonist: true
  setPreference: true
  visiblePreference: true
  objective: consent-be-rr-target-desc

# Box Antags
- type: antag
  id: DummyTroublemaker
  name: roles-antag-troublemaker-name
  antagonist: true
  setPreference: true
  visiblePreference: true
  objective: roles-antag-troublemaker-objective
  guides: [ Troublemaker ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 3600 # 1h

- type: antag
  id: DummyAcolyte
  name: roles-antag-acolyte-name
  antagonist: true
  setPreference: true
  visiblePreference: true
  objective: roles-antag-acolyte-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 3600 # 1h

# Other Fork Antags
## Hitman (DV)
- type: antag
  id: DummyHitman
  name: roles-antag-hitman-name
  antagonist: true
  setPreference: true
  visiblePreference: true
  objective: roles-antag-hitman-objective
  guides: [Hitman]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 3600 # 1h
