- type: entity
  name: honeycomb
  parent: FoodProduceBase
  id: FoodHoneyComb
  description: Crispy container of honey.
  components:
  - type: FlavorProfile
    flavors:
      - honeycomb
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 20
        reagents:
        - ReagentId: Honey
          Quantity: 5
        - ReagentId: Vitamin
          Quantity: 5
  - type: Sprite
    sprite: _NF/Objects/Specific/Hydroponics/bees.rsi
    state: produce
  - type: Extractable
    grindableSolutionName: food
    juiceSolution:
      reagents:
      - ReagentId: Honey
        Quantity: 5
  - type: Tag
    tags:
      - Vegetable
